### PR TITLE
Require rule sources from current working directory to be explicitly included

### LINKED ISSUE #760: Require rule sources from current working directory to be explicitly included
In v1 when calling PSRule cmdlets without `-Path` and `-Module` parameters, rule sources from the current working directory `$PWD` are automatically included.

Including `$PWD` is problematic in some scenarios such as build pipelines when rule sources may be stored in temporary paths such as `out/`. 

Now that the default recommend path `.ps-rule/` for standalone rules is automatically included also including `$PWD` is not required.

From v2 onwards,  `$PWD` should not be included unless `-Path .` or `-Path $PWD` is explicitly specified.

### LINKED ISSUE #939: Rule source gets loaded twice from PWD and .ps-rule/
**Description of the issue**

If you run `Get-PSRuleHelp` in a directory with `-Path $PWD` and `.ps-rule/`, rule sources get loaded twice and throws a `A rule with the same id '<rule ID>' already exists.` exception.

**To Reproduce**

Steps to reproduce the issue:

```powershell
Import-Module .\out\modules\PSRule
cd .\tests\PSRule.Tests\rules\
Get-PSRuleHelp
```

**Expected behaviour**

Exception should not be thrown, since there is only one rule with that ID. The file must be getting picked up twice - once from the top level `rules` directory and one more time in `.ps-rule/`.

This is expected with the new behavior from #610, where we throw an exception for duplicate rule IDs.  

**Error output**

```text
OperationStopped: A rule with the same id '.\Local.Common.1' already exists.
```

**Module in use and version:**

- Module: PSRule
- Version: **v2.0.0-B2201135**

Captured output from `$PSVersionTable`:

```text
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Additional context**

### PR DESCRIPTION
**Pull request by ArmaanMcleod**
## PR Summary

Fixes #760
Fixes #939

Added code changes to remove `$PWD` from `-Path` by default. 

## PR Checklist

- [x] PR has a meaningful title
- [x] Summarized changes
- [ ] Change is not breaking
- [ ] This PR is ready to merge and is not **Work in Progress**
- **Code changes**
  - [x] Have unit tests created/ updated
  - [x] Link to a filed issue
  - [x] [Change log](https://github.com/Microsoft/PSRule/blob/main/docs/CHANGELOG-v1.md) has been updated with change under unreleased section

### CODE REVIEW

File: src/PSRule/Pipeline/SourcePipeline.cs [hunk 1]
```diff
@@ -352,10 +342,29 @@ private static SourceFile[] IncludeFile(string path, string helpPath)
...
+                        StringComparison.OrdinalIgnoreCase),
+                    filePattern: "*.Rule.*");
+
+                return GetSourceFiles(filteredFiles, helpPath, moduleName);
+            }
+
+            var allFiles = System.IO.Directory.EnumerateFiles(path, "*.Rule.*", SearchOption.AllDirectories);
+
+            return GetSourceFiles(allFiles, helpPath, moduleName);
+        }
```
Comment (ArmaanMcleod) [inline src/PSRule/Pipeline/SourcePipeline.cs:362]: Used this workaround to filter out `ps-rule/` to fix the bug where files are searched twice. The `excludeDefaultRulePath` param basically ensures that directory is not searched, since by default `.ps-rule/` is searched during `Build()`.

Comment (ArmaanMcleod) [reply src/PSRule/Pipeline/SourcePipeline.cs:362]: Let me know if we need to change this behaviour.

File: src/PSRule/Pipeline/SourcePipeline.cs [hunk 2]
```diff
@@ -352,10 +342,28 @@ private static SourceFile[] IncludeFile(string path, string helpPath)
...
+
+            var filteredFiles = FilterFiles(
+                path,
+                directoryFilter: dir => !dir.Contains(
+                    DefaultRulePath.TrimEnd(Path.AltDirectorySeparatorChar),
+                    StringComparison.OrdinalIgnoreCase),
+                filePattern: "*.Rule.*");
+
+            return GetSourceFiles(filteredFiles, helpPath, moduleName);
+        }
```
Comment (ArmaanMcleod) [inline src/PSRule/Pipeline/SourcePipeline.cs:361]: Used this workaround to filter out `.ps-rule/` to fix the bug where files are searched twice. The excludeDefaultRulePath param basically ensures that directory is not searched, since by default `.ps-rule/` is searched during `Build()`.

Comment (ArmaanMcleod) [reply src/PSRule/Pipeline/SourcePipeline.cs:361]: Let me know if we need to change this behaviour. The other option I considered was just filtering directly from `EnumerateFiles`, but tried to create a solution where we can just ignore the directory on the initial scan.

Comment (BernieWhite) [reply src/PSRule/Pipeline/SourcePipeline.cs:361]: This part of the code is fairly tuned in terms of performance ops/ mem. I'll have a look.

**Review by BernieWhite — APPROVED** [review]
@ArmaanMcleod Nice work! All good to merge.
